### ISSUE TITLE
Error: Nuxt is stuck at the generated time

### ISSUE THREAD

**Issue by sondh0127** [windicss/vue-windicss-preprocess#3]
I'm following the migration guide to convert from `nuxt-tailwind` to `windi`
But dev server stuck to generate these files.

![image](https://user-images.githubusercontent.com/62163604/108182402-8c8d1f00-713b-11eb-833a-ad813548595f.png)

Here is the "reproduce repo":
[https://github.com/sondh0127/nuxt21-windi](https://github.com/sondh0127/nuxt21-windi)

The problem is with third party libs: (e.g. vue-scroll component). 
https://github.com/sondh0127/nuxt21-windi/blob/fc448ece95cacf8ce6e759b3215834c4ac00489d/pages/index.vue#L25

- When I commented out vue-scroll, the process is still stuck.
![image](https://user-images.githubusercontent.com/62163604/108182777-f7d6f100-713b-11eb-9ade-2f66f726a8ed.png)

- If I remove the vue-scroll component, the generated process will be finished.
![image](https://user-images.githubusercontent.com/62163604/108182646-d0802400-713b-11eb-8fcb-370cdfe74783.png)

**Comment by desislavsd** [comment]
It is stuck for me as well. Also I noticed in the task manager that the corresponding node process keeps the processor busy; A don't have `vue-scroll` installed. ( nuxt@2.14.15 )

**Comment by hannoeru** [comment]
~~Fixed in 2.1.0~~

**Comment by schneefux** [comment]
I have a large project with many third party dependencies and this problem is still present in 2.1.0

**Comment by victorgarciaesgi** [comment]
I have a very large nuxt project too and i've followed guides for nuxt and the build is stuck here (it seems random)
![image](https://user-images.githubusercontent.com/15092120/109488684-29c64c80-7a86-11eb-85c4-bbdcf431a41e.png)

**Comment by adam-nygate** [comment]
I'm facing a similar and believe it to be caused by using `<style>` tags on pages/components/layouts (in nuxt). Removing these tags allows the build to progress.

@sondh0127 @schneefux @victorgarciaesgi are you able to confirm whether you have .vue files with `<style>` tags and whether removing them resolves the issue?

**Comment by victorgarciaesgi** [comment]
@adam-nygate Yes I have `<style>` on my layout components, i will try to remove it!
 I will also try the module `nuxt-windicss`
